name: build-mrs
on:
  push:
    paths: ["emby.yaml"]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download converter
        run: |
          curl -L https://github.com/MetaCubeX/clash-ruleset-converter/releases/latest/download/clash-ruleset-converter-linux-amd64 -o converter
          chmod +x converter
      - name: Convert
        run: ./converter --input emby.yaml --behavior domain --output emby.mrs
      - uses: actions/upload-artifact@v4
        with:
          name: emby-mrs
          path: emby.mrs
